linters-settings:
  gocyclo:
      min-complexity: 24
  cyclop:
      max-complexity: 24
  forbidigo:
    forbid:
      - .*\.fatal,*
      - fmt.Print.*

linters:
  enable-all: true

  disable:
    - funlen
    - depguard
    - execinquery
    - exhaustive
    - exhaustruct
    - gomnd
    - ireturn
    - varnamelen
    - tagalign
    - wastedassign

run:
  timeout: 10m
  tests: false