services:

  postgresdb:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerqwer
    ports:
      - "5432:5432"
