name: CI
on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go test -race ./...

  build:
    strategy:
      matrix:
        go-version: [ ^1.22 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
      - uses: action/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go build ./cmd/service/main